### ISSUE TITLE
Element div not allowed as child of element h4 in this context

### ISSUE THREAD

**Issue by mKoonrad** [CodyHouse/cd-list-v2-changelog#1]
I found issue with List v2 component (--ul version) when I checked my project with [html validator](https://validator.w3.org/). Element div not allowed as child of element h4 in this context. I don't know how can I fix this code to pass this test. 

![image](https://user-images.githubusercontent.com/11725227/160027989-5e6e4ede-d720-4709-a0d9-c30c818101fe.png)
![image](https://user-images.githubusercontent.com/11725227/160027907-e66134af-b74c-43c2-911e-00353f11f931.png)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up! We have updated the component to fix this issue. You can get the updated code here:
http://localhost:3000/codyhouse-main/ds/components/app/list-v2--ul

Feel free to reopen the issue if you are still experiencing problems.

Cheers!
